name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_and_build:
    name: Build and push Docker image to docker hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          token: ${{ secrets.DOCKER_TOKEN }}
          
    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        context: .
        push: true
        tags: andim202/my-repository:latest
